#!/usr/bin/env python3
"""Generate README.md and the aggregated exports from data/resources/*.yml.

Run:  python scripts/build.py          # write files
      python scripts/build.py --check  # fail if the committed files are stale
"""
from __future__ import annotations

import argparse
import json
import sys
from collections import Counter, defaultdict
from pathlib import Path

# Runnable from anywhere: CONTRIBUTING tells contributors to use
# `python scripts/validate.py` from the repo root, which puts the repo root on
# sys.path rather than this directory.
sys.path.insert(0, str(Path(__file__).resolve().parent))

import yaml

from common import DATA, ROOT, anchor, load_all, subcategory_order
from flags import flag

README = ROOT / "README.md"
BY_REGULATION = ROOT / "docs" / "BY-REGULATION.md"
EXPORT_YML = DATA / "ecosystem.yml"
EXPORT_JSON = DATA / "ecosystem.json"

GENERATED = (
    "<!-- This file is generated by scripts/build.py from data/resources/*.yml. "
    "Edit the data, not this file. -->"
)

HEADER = """# Awesome EU Cybersecurity [![Awesome](https://awesome.re/badge-flat2.svg)](https://awesome.re)

> The regulations, certification schemes, agency standards and open-source tools
> that the European cybersecurity ecosystem actually runs on.

[![Validate](https://github.com/{repo}/actions/workflows/validate.yml/badge.svg)](https://github.com/{repo}/actions/workflows/validate.yml)
[![Link check](https://github.com/{repo}/actions/workflows/link-check.yml/badge.svg)](https://github.com/{repo}/actions/workflows/link-check.yml)
[![Entries](https://img.shields.io/badge/entries-{count}-0B5FFF)](#contents)
[![Countries](https://img.shields.io/badge/countries%20%26%20bodies-{countries}-0B5FFF)](#coverage)
[![License: CC0-1.0](https://img.shields.io/badge/license-CC0--1.0-lightgrey.svg)](LICENSE)

Europe has spent the last few years turning cybersecurity into law. NIS2 for
critical sectors, DORA for finance, the Cyber Resilience Act for anything shipped
with a digital element, eIDAS 2 for identity and trust services, the AI Act layered
over all of it, plus the sectoral rules that rarely make the headlines, like the
network code for electricity, Part-IS for aviation, and the 5G Toolbox. Each one
arrived with its own regulators, certification schemes, deadlines and, eventually,
its own body of implementation material.

That material is real and a lot of it is very good. It is also scattered: across
twenty-seven national agencies, several publishing only in their own language;
across ENISA, the ESAs, ETSI and CENELEC; across EU-funded research projects that
shipped working code and then went quiet; and across GitHub organisations that
almost nothing links to from anywhere obvious, among them CIRCL, CERT Polska,
ANSSI, BSI and the EU Digital Identity Wallet. Meanwhile the tooling most teams
reach for by default is American, and the European equivalent, often the one the
regulator itself built and published, goes unused.

So this is the index. Every entry has had its URL opened and its content checked
against the claim made about it. Anything that could not be verified was dropped
rather than guessed, which is why some sections here are short: that is the honest
shape of the ecosystem, not a gap in the research.

**Arrived here with a specific obligation rather than a topic?**
[`docs/BY-REGULATION.md`](docs/BY-REGULATION.md) slices the same entries by the
instrument that puts them in scope: NIS2, DORA, the CRA, GDPR, the AI Act,
eIDAS, the certification schemes, the EECC and the post-quantum transition.

### What belongs here

A resource earns a place if it addresses an EU regulation (NIS2, DORA, GDPR, CRA,
the AI Act, eIDAS), an EU or national technical standard or certification scheme
(EUCC, EUCS, SecNumCloud, BSI C5, IT-Grundschutz, ENS), or is maintained by a
European body, government, university or EU-funded project.

Standards and agency guidance count for as much as code here. A PDF from ANSSI is
a first-class entry, because for a lot of these problems the PDF *is* the
deliverable.
Where there is tooling, free and open-source comes first; closed products appear
only where they are sovereign infrastructure or an official registry with no open
equivalent, and they are marked `[Commercial]` so you can see them coming.

What stays out: generic security tooling with no EU angle however good it is,
vendor marketing, exam prep, conference listings, and raw legal text with no
implementation value beyond the regulation itself.
"""

LEGEND = """## Legend

| Marker | Meaning |
| --- | --- |
| `[Open Source]` | Source code is public under an open-source licence. |
| `[EU-Hosted]` | Service operated on infrastructure run by an EU body or member state. |
| `[Commercial]` | Closed or paid. Present only as sovereign infrastructure or an official registry, always with a note saying why. |
| `Tool` `Standard` `Framework` `Guideline` `Certification Scheme` `Report` `Feed` | What kind of resource it is. |
| 🇪🇺 🇩🇪 🇫🇷 … | Who maintains it. |

A ⚠️ means `confidence: medium`: the resource is real and the link resolves, but
its EU framing or its maintenance status rests on thinner evidence than the rest.
Worth a second look before you rely on it.
"""

FOOTER = """## Contributing

Corrections are as welcome as additions, arguably more so. A link that has rotted,
a project quietly archived, an entry whose EU framing does not survive a careful
read: all of those are worth an issue.

Open a [resource proposal](../../issues/new?template=add_resource.yml) or send a
pull request editing the relevant file under [`data/resources/`](data/resources).
`README.md` is generated from that data, so please do not edit it directly; CI
will tell you off. [CONTRIBUTING.md](CONTRIBUTING.md) has the scope rules and the
one bar that really matters: **do not add a resource you have not opened yourself.**

Adding one entry is a one-file change and takes about five minutes:

```bash
git clone https://github.com/{repo} && cd awesome-eu-cybersec
make install
$EDITOR data/resources/<category-slug>.yml
make build     # regenerates this file and the exports
make check     # the same thing CI runs
```

**Looking for something specific to do?** The
[`good first issue`](../../labels/good%20first%20issue) label holds pre-scoped
gaps, each naming the file to edit and what is missing. The
[`country gap`](../../labels/country%20gap) ones are the most useful: several EU
and EEA member states have no national-authority entry at all, and the person
best placed to fix that is usually someone who works in that country.

Contributors are credited in [CONTRIBUTORS.md](CONTRIBUTORS.md).

If you work at a national agency or CSIRT and we have listed your work wrongly, or
missed something you think belongs, please say so. That feedback is worth more than
any amount of searching from the outside.

## License

[![CC0](https://licensebuttons.net/p/zero/1.0/88x31.png)](LICENSE)

To the extent possible under law, the contributors have waived all copyright and
related rights to this compilation under [CC0 1.0 Universal](LICENSE). The linked
resources remain under their own licences.
"""


def render_entry(entry: dict) -> str:
    badges = [f"{flag(entry['country_or_body'])} `{entry['country_or_body']}`", f"`{entry['entry_type']}`"]
    if entry.get("hosting_note"):
        badges.append(f"`{entry['hosting_note']}`")
    if entry.get("license"):
        badges.append(f"`{entry['license']}`")
    if entry.get("confidence") == "medium":
        badges.append("⚠️")

    line = f"- [{entry['name']}]({entry['url']}) - {entry['description']} " + " ".join(badges)
    if entry.get("repo"):
        line += f" ([source]({entry['repo']}))"
    if entry.get("notes"):
        line += f"\n  <br><sub>{entry['notes']}</sub>"
    return line


def render_readme(categories, entries_by_slug, repo: str) -> str:
    total = sum(len(v) for v in entries_by_slug.values())
    # Count jurisdictions, not "Country/Agency" pairs, so the badge agrees with
    # the coverage table further down.
    bodies = {
        e["country_or_body"].split("/", 1)[0].strip()
        for v in entries_by_slug.values()
        for e in v
    }

    parts = [
        HEADER.format(repo=repo, count=total, countries=len(bodies)),
        GENERATED,
        "",
        LEGEND,
        "## Contents",
        "",
    ]

    for category in categories:
        heading = f"{category.emoji} {category.name}".strip()
        count = len(entries_by_slug[category.slug])
        parts.append(f"- [{heading}](#{anchor(heading)}) ({count})")
        for sub in subcategory_order(category, entries_by_slug[category.slug]):
            n = sum(1 for e in entries_by_slug[category.slug] if e["subcategory"] == sub)
            if n:
                parts.append(f"  - [{sub}](#{anchor(sub)}) ({n})")
    parts += ["- [Coverage](#coverage)", "- [Contributing](#contributing)", ""]

    for category in categories:
        entries = entries_by_slug[category.slug]
        heading = f"{category.emoji} {category.name}".strip()
        parts += [f"## {heading}", "", category.description, ""]

        rendered_subs = set()
        for sub in subcategory_order(category, entries):
            items = sorted(
                (e for e in entries if e["subcategory"] == sub),
                key=lambda e: e["name"].lower(),
            )
            if not items:
                continue
            rendered_subs.add(sub)
            parts += [f"### {sub}", ""]
            parts += [render_entry(e) for e in items]
            parts.append("")

        orphans = sorted({e["subcategory"] for e in entries} - rendered_subs)
        if orphans:  # validate.py rejects these, but never silently drop data
            parts += [f"### {o}" for o in orphans]

    parts += [render_coverage(categories, entries_by_slug), FOOTER.format(repo=repo)]
    return "\n".join(parts).rstrip() + "\n"


def render_coverage(categories, entries_by_slug) -> str:
    all_entries = [e for v in entries_by_slug.values() for e in v]
    by_country = Counter(e["country_or_body"].split("/")[0] for e in all_entries)
    by_type = Counter(e["entry_type"] for e in all_entries)
    open_source = sum(1 for e in all_entries if "[Open Source]" in (e.get("hosting_note") or ""))

    rows = [
        "## Coverage",
        "",
        f"{len(all_entries)} verified entries spanning {len(by_country)} countries and EU bodies, "
        f"{open_source} of them open-source tooling. The uneven distribution is real: "
        "some sectors have a mature European toolchain, others have a regulation and "
        "not much else yet.",
        "",
        "| Category | Entries |",
        "| --- | ---: |",
    ]
    for category in categories:
        rows.append(f"| {category.name} | {len(entries_by_slug[category.slug])} |")

    rows += ["", "| Country or body | Entries |", "| --- | ---: |"]
    for country, n in by_country.most_common():
        rows.append(f"| {flag(country)} {country} | {n} |")

    rows += ["", "| Resource type | Entries |", "| --- | ---: |"]
    for kind, n in by_type.most_common():
        rows.append(f"| {kind} | {n} |")

    rows.append("")
    return "\n".join(rows)


# Most readers arrive with a regulation, not a category: "we are in scope for
# NIS2, now what". Each bucket matches on tags first, then on description text.
REGULATIONS = [
    ("NIS2", "Directive (EU) 2022/2555", ("nis2",), ("nis2", "nis 2")),
    ("DORA", "Regulation (EU) 2022/2554", ("dora", "tlpt", "tiber"), ("dora",)),
    ("Cyber Resilience Act", "Regulation (EU) 2024/2847", ("cra", "sbom", "csaf"),
     ("cyber resilience act", "cra ",)),
    ("GDPR", "Regulation (EU) 2016/679", ("gdpr", "dpia", "pet", "anonymization"), ("gdpr",)),
    ("EU AI Act", "Regulation (EU) 2024/1689", ("ai-act",), ("ai act",)),
    ("eIDAS", "Regulation (EU) 910/2014 and 2024/1183", ("eidas", "eudi-wallet", "qtsp", "trusted-list"),
     ("eidas", "digital identity wallet")),
    ("Cybersecurity Act certification", "EUCC, EUCS and national schemes",
     ("eucc", "eucs", "certification", "secnumcloud", "common-criteria"),
     ("eucc", "eucs", "certification scheme", "secnumcloud")),
    ("EECC and the 5G Toolbox", "Directive (EU) 2018/1972",
     ("eecc", "5g", "5g-toolbox", "open-ran"), ("eecc", "5g toolbox")),
    ("Post-quantum transition", "Recommendation (EU) 2024/1101", ("pqc", "qkd"),
     ("post-quantum", "quantum")),
]


def _matches(entry: dict, tags: tuple[str, ...], phrases: tuple[str, ...]) -> bool:
    if set(entry.get("tags", [])) & set(tags):
        return True
    text = f"{entry['name']} {entry['description']}".lower()
    return any(phrase in text for phrase in phrases)


def render_by_regulation(categories, entries_by_slug) -> str:
    flat = [
        {"category": c.name, **e} for c in categories for e in entries_by_slug[c.slug]
    ]
    parts = [
        "# By regulation",
        "",
        GENERATED,
        "",
        "A cross-index of the same entries as [`README.md`](../README.md), grouped by the",
        "instrument that puts them in scope. An entry can appear under more than one",
        "heading, and an entry that appears under none is still in scope through its",
        "maintainer rather than through a specific regulation.",
        "",
    ]
    for title, citation, tags, phrases in REGULATIONS:
        hits = sorted(
            (e for e in flat if _matches(e, tags, phrases)), key=lambda e: e["name"].lower()
        )
        parts += [f"## {title}", "", f"*{citation}* - {len(hits)} entries", ""]
        for entry in hits:
            parts.append(
                f"- [{entry['name']}]({entry['url']}) - {entry['description']} "
                f"{flag(entry['country_or_body'])} `{entry['country_or_body']}` "
                f"<sub>{entry['category']}</sub>"
            )
        parts.append("")
    return "\n".join(parts).rstrip() + "\n"


def render_exports(categories, entries_by_slug) -> tuple[str, str]:
    flat = []
    for category in categories:
        for entry in entries_by_slug[category.slug]:
            flat.append({"category": category.name, **entry})

    yml = (
        "# GENERATED by scripts/build.py - do not edit.\n"
        "# Flat export of data/resources/*.yml for downstream consumers.\n"
        + yaml.safe_dump(flat, sort_keys=False, allow_unicode=True, width=100)
    )
    js = json.dumps(
        {"version": 1, "count": len(flat), "entries": flat}, indent=2, ensure_ascii=False
    ) + "\n"
    return yml, js


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    parser.add_argument("--repo", default="mdiamantino/awesome-eu-cybersec", help="owner/name for badges")
    args = parser.parse_args()

    categories, entries_by_slug = load_all()
    readme = render_readme(categories, entries_by_slug, args.repo)
    export_yml, export_json = render_exports(categories, entries_by_slug)

    targets: list[tuple[Path, str]] = [
        (README, readme),
        (BY_REGULATION, render_by_regulation(categories, entries_by_slug)),
        (EXPORT_YML, export_yml),
        (EXPORT_JSON, export_json),
    ]

    if args.check:
        stale = [p.name for p, content in targets if not p.exists() or p.read_text(encoding="utf-8") != content]
        if stale:
            print("stale generated files: " + ", ".join(stale))
            print("run: make build   (or: python3 scripts/build.py) and commit the result")
            return 1
        print("generated files are up to date")
        return 0

    for path, content in targets:
        path.write_text(content, encoding="utf-8")
        print(f"wrote {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
