#!/usr/bin/env python3
"""Merge staged research output into data/resources/*.yml.

Staged files are flat YAML lists carrying a `category:` key per entry. Entries
whose URL is already present are skipped; everything else is normalised, stamped
with `last_verified`, and appended to the right category file.

Run:  python scripts/ingest.py <staging-dir> [--verified YYYY-MM-DD]
"""
from __future__ import annotations

import argparse
import datetime as dt
import sys
from pathlib import Path

import yaml

from common import RESOURCES, load_categories, load_resource_file

ALLOWED_KEYS = {
    "name", "url", "repo", "description", "subcategory", "tags", "entry_type",
    "country_or_body", "hosting_note", "license", "confidence", "last_verified", "notes",
}


def normalise(entry: dict, verified: str) -> dict:
    out: dict = {}
    for key in ("name", "url", "repo", "description", "subcategory"):
        if entry.get(key):
            out[key] = str(entry[key]).replace("&amp;", "&").strip()

    out["tags"] = [t.strip().lower().replace(" ", "-") for t in entry.get("tags", []) if t][:5]
    out["entry_type"] = entry["entry_type"].strip()
    out["country_or_body"] = entry.get("country_or_body", "EU").replace("&amp;", "&").strip()

    hosting = (entry.get("hosting_note") or "").strip()
    if hosting:
        out["hosting_note"] = hosting
    if entry.get("license"):
        out["license"] = entry["license"].strip()
    if entry.get("notes"):
        out["notes"] = " ".join(entry["notes"].split())

    out["confidence"] = entry.get("confidence", "medium").strip()
    out["last_verified"] = entry.get("last_verified", verified)

    unknown = set(entry) - ALLOWED_KEYS - {"category", "verified_note"}
    if unknown:
        print(f"  note: dropped unsupported keys on {out['name']!r}: {sorted(unknown)}")
    return {k: v for k, v in out.items() if k in ALLOWED_KEYS}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("staging", type=Path)
    parser.add_argument("--verified", default=dt.date.today().isoformat())
    args = parser.parse_args()

    categories = load_categories()
    by_name = {c.name: c for c in categories}
    existing_urls = {
        e["url"].rstrip("/").lower()
        for c in categories
        for e in load_resource_file(c).get("entries", [])
    }

    staged: dict[str, list[dict]] = {}
    for path in sorted(args.staging.glob("*.yml")):
        entries = yaml.safe_load(path.read_text(encoding="utf-8")) or []
        print(f"{path.name}: {len(entries)} staged")
        for entry in entries:
            category_name = entry["category"].replace("&amp;", "&").strip()
            if category_name not in by_name:
                print(f"  SKIP unknown category {category_name!r} for {entry['name']!r}")
                continue
            url = entry["url"].rstrip("/").lower()
            if url in existing_urls:
                print(f"  SKIP duplicate URL: {entry['name']}")
                continue
            existing_urls.add(url)
            staged.setdefault(by_name[category_name].slug, []).append(
                normalise(entry, args.verified)
            )

    added = 0
    for slug, new_entries in staged.items():
        category = next(c for c in categories if c.slug == slug)
        doc = load_resource_file(category)
        doc.setdefault("entries", []).extend(new_entries)
        doc["entries"].sort(key=lambda e: (e["subcategory"], e["name"].lower()))
        header = (
            f"# {category.name}\n"
            "# Edit entries here; README.md is generated by scripts/build.py.\n"
        )
        body = yaml.safe_dump(doc, sort_keys=False, allow_unicode=True, width=100)
        (RESOURCES / f"{slug}.yml").write_text(header + body, encoding="utf-8")
        added += len(new_entries)
        print(f"{slug}: +{len(new_entries)} -> {len(doc['entries'])}")

    print(f"\nadded {added} entries")
    return 0


if __name__ == "__main__":
    sys.exit(main())
